complete -c fimfic-tracker -n "__fish_use_subcommand" -s c -l config -d 'Extra config file to use' -r -F
complete -c fimfic-tracker -n "__fish_use_subcommand" -l color -d 'When to use colors' -r -f -a "{auto	Use colored output if writing to a terminal/TTY,always	Always use colored output,never	Never use colored output}"
complete -c fimfic-tracker -n "__fish_use_subcommand" -s v -l verbose -d 'Shows verbose output, can be used multiple times to set level of verbosity'
complete -c fimfic-tracker -n "__fish_use_subcommand" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c fimfic-tracker -n "__fish_use_subcommand" -s V -l version -d 'Print version'
complete -c fimfic-tracker -n "__fish_use_subcommand" -f -a "track" -d 'Adds stories for tracking and downloads them'
complete -c fimfic-tracker -n "__fish_use_subcommand" -f -a "untrack" -d 'Untracks stories'
complete -c fimfic-tracker -n "__fish_use_subcommand" -f -a "list" -d 'List all stories that are being tracked'
complete -c fimfic-tracker -n "__fish_use_subcommand" -f -a "download" -d 'Checks for updates on tracking list and downloads them if so'
complete -c fimfic-tracker -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c fimfic-tracker -n "__fish_seen_subcommand_from track" -s o -l overwrite -d 'Overwrites already present stories on cached data'
complete -c fimfic-tracker -n "__fish_seen_subcommand_from track" -s s -l skip-download -d 'Don\'t download stories, only updates cached data'
complete -c fimfic-tracker -n "__fish_seen_subcommand_from track" -s h -l help -d 'Print help'
complete -c fimfic-tracker -n "__fish_seen_subcommand_from untrack" -s h -l help -d 'Print help'
complete -c fimfic-tracker -n "__fish_seen_subcommand_from list" -l sort-by -d 'Sort stories by the given key' -r -f -a "{id	,title	,author	,chapters	,words	,update	}"
complete -c fimfic-tracker -n "__fish_seen_subcommand_from list" -s s -l short -d 'Show only the ID and title of each tracked story'
complete -c fimfic-tracker -n "__fish_seen_subcommand_from list" -s r -l reverse -d 'Reverse the order of the list'
complete -c fimfic-tracker -n "__fish_seen_subcommand_from list" -l show-complete -l complete -d 'Show stories marked as Complete'
complete -c fimfic-tracker -n "__fish_seen_subcommand_from list" -l show-incomplete -l incomplete -d 'Show stories marked as Incomplete'
complete -c fimfic-tracker -n "__fish_seen_subcommand_from list" -l show-hiatus -l hiatus -d 'Show stories marked as On Hiatus'
complete -c fimfic-tracker -n "__fish_seen_subcommand_from list" -l show-cancelled -l cancelled -d 'Show stories marked as Cancelled'
complete -c fimfic-tracker -n "__fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c fimfic-tracker -n "__fish_seen_subcommand_from download" -s f -l force -d 'Download no matter the presence of updates'
complete -c fimfic-tracker -n "__fish_seen_subcommand_from download" -s y -l yes -d 'Automatically answers prompts with Y'
complete -c fimfic-tracker -n "__fish_seen_subcommand_from download" -s n -l no -d 'Automatically answers prompts with N'
complete -c fimfic-tracker -n "__fish_seen_subcommand_from download" -s h -l help -d 'Print help'
complete -c fimfic-tracker -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from track; and not __fish_seen_subcommand_from untrack; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from help" -f -a "track" -d 'Adds stories for tracking and downloads them'
complete -c fimfic-tracker -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from track; and not __fish_seen_subcommand_from untrack; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from help" -f -a "untrack" -d 'Untracks stories'
complete -c fimfic-tracker -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from track; and not __fish_seen_subcommand_from untrack; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List all stories that are being tracked'
complete -c fimfic-tracker -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from track; and not __fish_seen_subcommand_from untrack; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from help" -f -a "download" -d 'Checks for updates on tracking list and downloads them if so'
complete -c fimfic-tracker -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from track; and not __fish_seen_subcommand_from untrack; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
